services:
  account-mgr-postgres:
    container_name: account-mgr-db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: account_mgr_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  account-mgr-valkey:
    container_name: account-mgr-vk
    image: valkey/valkey:latest
    restart: always
    environment:
      - VALKEY_PASSWORD=magical_password
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data

volumes:
  postgres_data:
  valkey_data:
