services:
  account-mgr:
    container_name: account-mgr
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    restart: always
    depends_on:
      - account-mgr-postgres
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@account-mgr-postgres:5432/account_mgr_db
      ENVIRONMENT: local
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5005"]

  account-mgr-postgres:
    container_name: account-mgr-db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: account_mgr_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  account-mgr-vk:
    container_name: account-mgr-vk
    image: valkey/valkey:latest
    restart: always
    command: ["valkey-server", "/usr/local/etc/valkey/valkey.conf"]
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
      - ./valkey.conf:/usr/local/etc/valkey/valkey.conf

volumes:
  postgres_data:
  valkey_data:
