services:
    account-manager:
        container_name: account-manager
        build:
            context: ../
            dockerfile: Dockerfile
        ports:
            - '5000:5000'
        restart: always
        env_file:
          - ../.env.production
        command: ['python', 'app.py']
