services:
  account-mgr:
    container_name: account-mgr
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    restart: always
    depends_on:
      - account-mgr-postgres
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@account-mgr-postgres:5432/account_mgr_db
      ENVIRONMENT: local
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5005"]

  account-mgr-postgres:
    container_name: account-mgr-db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: account_mgr_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
