name: Pull Request Pipeline

on:
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Bandit Security Scan
        run: bandit -r ./ --severity-level high --confidence-level all

      - name: Run Pip Audit
        run: pip-audit

      - name: Run Safety Security Check
        run: safety check -r requirements.txt

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio pytest-cov aiosqlite
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests with coverage
        run: |
          pytest tests/ -v --cov=. --cov-report=xml --cov-report=html

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            htmlcov/
            coverage.xml
          retention-days: 7

      - name: Coverage Summary
        run: |
          echo "Coverage Summary:"
          python -c "import xml.etree.ElementTree as ET; print(f'Total Coverage: {ET.parse(\"coverage.xml\").getroot().get(\"line-rate\")}%')"
