name: DevSecOps Pipeline

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0" # Weekly scan on Sundays
  workflow_dispatch:

jobs:
  dependency-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Bandit Security Scan
        run: bandit -r ./ --severity-level high --confidence-level all

      - name: Run Pip Audit
        run: pip-audit

      - name: Run Safety Security Check
        run: safety check -r requirements.txt

      - name: OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "queuetopia-account"
          path: "."
          format: "HTML"
          out: "reports"

      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports/

  static-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install pylint

      - name: Run Python Code Quality Checks
        run: pylint --disable=all --enable=security,typing,imports *.py

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

  secret-scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for hardcoded secrets
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .github/gitleaks.toml

  infrastructure-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Scan Dockerfile
        uses: hadolint/hadolint-action@v3.1.0

  container-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: account-mgr:latest
          load: true

      - name: Docker image scan
        uses: anchore/scan-action@v3
        with:
          image: "account-mgr:latest"
          fail-build: true

  license-compliance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pip-licenses

      - name: Check for license compliance
        run: pip-licenses --format=json --with-license-file --with-urls > license-report.json

      - name: Upload License Report
        uses: actions/upload-artifact@v4
        with:
          name: license-report
          path: license-report.json

  security-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run security unit tests
        run: pytest tests/ --cov=. --cov-report=xml -m security || true

  sbom-generation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          format: spdx-json
          output-file: sbom.spdx.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.spdx.json
